
export const VunetSidebarConstants = {
  ANALYTICS: 'Analytics',
  STORYBOARDS: 'Storyboards',
  // DASHBOARDS: 'Dashboards',
  DASHBOARDS: 'Storyboards',
  SEARCH: 'Search',
  EVENTS: 'Events',
  REPORTS: 'Reports',
  ANALYTICS_CONFIGURATIONS: 'Analytics Configurations',
  VISUALIZATIONS: 'Visualizations',
  ALERT_RULES: 'Alert Rules',
  ANOMALY_DETECTION: 'Anomaly Detection',
  MANAGE_RESOURCES: 'Manage Resources',
  NETWORK_CONFIGURATION: 'Network Configuration',
  DEVICE_CONFIGURATION: 'Device Configuration',
  DATA: 'Data',
  SOURCES: 'Sources',
  VUBLOCK: 'vuModule',
  HOST_LANDSCAPE: 'Host Landscape',
  ENRICH: 'Enrich',
  DATA_STORE: 'Data Store',
  STORAGE: 'Storage',
  FILES: 'Files',
  DATA_RETENTION_SETTINGS: 'Data Retention Settings',
  SETTINGS: 'Settings',
  BACKUP: 'Backup',
  PREFERENCES: 'Preferences',
  DEFINITIONS: 'Definitions',
  USER: 'User',
  VUBLOCK_STORE: 'vuBlock Store',
  LICENSE_USAGE: 'License Usage',
  ABOUT: 'About',
  IMAGEMANAGR: 'Manage Images',
  NETWORK: 'Network',
  DISCOVERY: 'Discovery',
  ASSETS: 'Assets',
  PIIDATA: 'PII Data',
  NETWORKMAP: 'Network Map',
  PERMISSION_VIEW_OBJECT: 'ViewObject',
  PERMISSION_MANAGE_OBJECT: 'ManageObject',
  PERMISSION_MANAGE_DATA_SOURCES: 'ManageDataSources',
  PERMISSION_MANAGE_DATA_ENRICHMENT: 'ManageDataEnrichment',
  PERMISSION_MANAGE_DATA_SETTINGS: 'ManageDataSettings',
  PERMISSION_MANAGE_FILES: 'ManageFiles',
  PERMISSION_MANAGE_PREFERENCES: 'ManagePreferences',
  PERMISSION_MANAGE_USERS: 'ManageUsers',
  PERMISSION_MANAGE_LICENSE: 'ManageLicense',
  PERMISSION_MANAGE_AGENT: 'ManageAgent',
  PERMISSION_DATA_FETCH_APIS: 'DataFetchAPIs',
  PERMISSION_MANAGE_DIAGNOSTIC: 'ManageDiagnostic',
  PERMISSION_MANAGE_NETWORK: 'ManageNetwork',
  PERMISSION_PII_DATA: 'ManagePIIData'
};
