language: node_js
node_js:
- '0.10'
install:
- npm install -g grunt-cli bower
- npm install
- bower install
script:
- npm test
notifications:
  email:
  - rashid.khan@elasticsearch.com
  hipchat:
    rooms:
      secure: BYXpMi8WiOM/ONeqnMqruhr/OUW93rVJ38sltpARoUQJSMcZYecnSZDWIthTWy3cOIECn4gRWcFYMxdF9VTTOe0dg2m4bGg+EnsxA2+Exjv3s8JPFJOczqBGnJud8DPOOCTVxKIAQMbfd6qvudAQaii7JknOGHjSnwNWT/IL6rI=
    format: html
    template:
      - '%{repository}/%{branch} #%{build_number} by %{author}): %{message} (<a href="%{build_url}">open</a>)'