language: node_js
node_js:
- '0.10'
install:
- npm install -g grunt-cli bower
- npm install
- bower install
script:
- npm test
notifications:
  email:
  - rashid.khan@elasticsearch.com
  hipchat:
    rooms:
      secure: lcRkWO1DIrU778TuklKrLG9caBeTtc/zeyM36zJo1Ms4skTALNWk/+xayrebbAABS0AekRG5FlAHoRhx+Z57GcUJGe1y3SRTh5qTVRQmSODTv7lMyeu+md8B5yNY4+5hINrwzWO4NJr/PIrMAlnHIGIADerZRsZWSbf7xvqUcl0=
