# Kibana is served by a backend server. This controls which port to use.
port: 5601

# The Elasticsearch instance to use for all your queries
elasticsearch: "http://localhost:9200"

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create an new index if it doesn't already exist.
kibanaIndex: "kibana-int"

# The default application to laad.
defaultAppId: "discover"
